<a href="https://colab.research.google.com/github/agarwalsourabh55/Deep-learning/blob/deep_learning_dev/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

## Create the Empty Tensor
x= torch.empty(3)
print(x)
x= torch.empty(2,3)
x= torch.empty(2,2,3)

tensor([7.2105e-37, 0.0000e+00, 4.4842e-44])


In [2]:
## Creating torch with random values 

In [4]:
torch.randn(2,3)

tensor([[ 0.7233,  0.0378, -0.9199],
        [ 1.4418, -1.2958, -0.3074]])

In [5]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [7]:
## Giving Specific Data type
x.dtype  ## default float.32
x= torch.ones(2,2,dtype=  torch.double)
print(x.size())

torch.Size([2, 2])


In [8]:
x= torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [9]:
x= torch.randn(2,2)
y= torch.randn(2,2)
print(x)
print(y)

tensor([[-0.4172,  0.2090],
        [ 0.5973, -0.6693]])
tensor([[ 1.6284, -1.3117],
        [ 0.0707, -0.1412]])


In [11]:
## Addition
z= x+y
print(z) # Element wise addition

tensor([[ 1.2112, -1.1028],
        [ 0.6680, -0.8105]])


In [12]:
z= torch.add(x,y)
print(z)

tensor([[ 1.2112, -1.1028],
        [ 0.6680, -0.8105]])


In [14]:
## inplace addition
y.add_(x) ## will modify y

## Every funciton that has _ aat the last will do the inplace operation

tensor([[ 0.7940, -0.8938],
        [ 1.2653, -1.4798]])

In [15]:
## substaraction
z= x-y
z=torch.sub(x,y)


In [16]:
## Multipliacatino
y.mul_(x)

tensor([[-0.3312, -0.1868],
        [ 0.7557,  0.9904]])

In [17]:
## division 
torch.div(x,y)

tensor([[ 1.2595, -1.1188],
        [ 0.7904, -0.6758]])

In [19]:
## slicing Operations

x= torch.rand(5,3)
print(x[:,0])
print(x)

tensor([0.3283, 0.7036, 0.6271, 0.6988, 0.4320])
tensor([[0.3283, 0.1578, 0.4797],
        [0.7036, 0.8818, 0.5780],
        [0.6271, 0.4285, 0.4365],
        [0.6988, 0.3112, 0.2248],
        [0.4320, 0.7449, 0.2854]])


In [21]:
x[1,2]

tensor(0.5780)

In [22]:
## Willge tthe actual value
x[1,2].item()

0.5779715180397034

In [24]:
## reshaping operation
x= torch.rand(4,4)
print(x)
y= x.view(16)
print(y)

tensor([[0.2961, 0.9147, 0.7951, 0.4519],
        [0.0882, 0.6399, 0.0094, 0.0505],
        [0.4640, 0.1325, 0.9942, 0.0237],
        [0.6641, 0.5004, 0.4337, 0.2985]])
tensor([0.2961, 0.9147, 0.7951, 0.4519, 0.0882, 0.6399, 0.0094, 0.0505, 0.4640,
        0.1325, 0.9942, 0.0237, 0.6641, 0.5004, 0.4337, 0.2985])


In [27]:
y= x.view(-1,4)
print(y.size())

torch.Size([4, 4])


In [28]:
import numpy as np

#converting numpy to tensor
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [29]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [31]:
## Also added +1 to the b also..because they point to the same memory location
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [32]:
a= np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [33]:
b= torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [35]:
a+=1

In [37]:
## This happen only when you have tensor on the GPU
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [40]:
## checking cuda availability
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5,device = device)
  y = torch.ones(5)
  y= y.to(device)

  z= x+y
  z.numpy()## will return error because numpy only handle CPU tensors not GPU
  z = z.to("cpu")
else:
  print("not available")

not available


In [42]:

x = torch.ones(5,requires_grad = True)  ## tellthe pytroch that it will nees to calculate the gradients
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [53]:
## Autgrad package and Calculating Gradients
import torch
x= torch.randn(3,requires_grad = True)
print(x)

tensor([0.9422, 1.3274, 0.2494], requires_grad=True)


In [54]:
y = x+2 ## will create the computational graph    x                      this is forward pass
                                                      # +   y
                                                  # 2
## pytorch will automatically create the function that will later use to creat the backpropogation function_name = Addbackward

print(y)

tensor([2.9422, 3.3274, 2.2494], grad_fn=<AddBackward0>)


In [55]:
z= y*y*2
print(z)


tensor([17.3136, 22.1426, 10.1199], grad_fn=<MulBackward0>)


In [56]:
z= z.mean()
print(z)

tensor(16.5254, grad_fn=<MeanBackward0>)


In [57]:
z.backward() ## tocalulat ethe gradient of z with respect tox
print(x.grad)  ## x store that gradient
## in backward it will creat the vector of jacobian matrix

tensor([3.9230, 4.4365, 2.9992])


In [58]:
x= torch.randn(3,requires_grad= True)
y= x+2
z= y*y*2

# z.backward()
# print(x.grad)# this will give error need to add one line 

v = torch.tensor([0.1,1.0,0.001], dtype = torch.float32)
z.backward(v)
print(x.grad)

tensor([0.8598, 5.9732, 0.0117])


In [59]:
## Call the requires_grad_(False)
## x.detach() ## create new tensor that doesn't reauire gradieent
## with torch.no_grad():

x= torch.randn(3,requires_grad = True)
print(x)
x.requires_grad_(False)


tensor([ 1.5585, -0.6175, -1.0777], requires_grad=True)


tensor([ 1.5585, -0.6175, -1.0777])

In [60]:
y = x.detach()
print(y)

tensor([ 1.5585, -0.6175, -1.0777])


In [65]:
x= torch.randn(3,requires_grad = True)
with torch.no_grad():
  y = x+2
  print(y) ## y don't have gradient function
print(x) ## x has gradient

tensor([2.6250, 2.2028, 0.5080])
tensor([ 0.6250,  0.2028, -1.4920], requires_grad=True)


In [66]:
## Whenever we call the backward function the value will be accumulated in the x

In [74]:
weights = torch.ones(4,requires_grad = True)
for epoch in range(2):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()  # need to add this to prevent gradient to calculate on every iteration


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [83]:
weights = torch.ones(4,requires_grad = True)


optimizer = torch.optim.SGD([weights] , lr = 0.01)
optimizer.step()
optimizer.zero_grad()

In [86]:
weights = torch.ones(4,requires_grad = True)

## these are autograd package
# z.backward()
# weights.grad.zero_()

In [ ]:
## Backpropogation

## forward pass: compute Loss
## Compute local gradients
## Backward pass: Compute dLoss / dWeights using the Chain Rule
x = 